CREATE PROCEDURE SP_FATO_ESTADO
AS

IF EXISTS (SELECT * FROM SYSOBJECTS WHERE name = 'Fato_Estado')
   BEGIN
         TRUNCATE TABLE Fato_Estado
   END
ELSE
   BEGIN
      CREATE TABLE Fato_Estado(FATOESTID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	  NM_ESTADO Varchar(60) NULL, QTD_FUNCIONARIOS INT NULL)
   END

DECLARE @QF INT
DECLARE @CONTADOR INT
DECLARE @ESTADOSNM VARCHAR(60)
SET @CONTADOR = 1

WHILE @CONTADOR < 11
   BEGIN
      SELECT @QF=SUM(QTD_FUNCIONARIOS) FROM Fato_Cidade
	  WHERE ESTADO_ID = @CONTADOR
      SELECT @ESTADOSNM=NM_ESTADO FROM ESTADO
      WHERE ESTADOID=@CONTADOR
      SET @CONTADOR = @CONTADOR + 1
      INSERT INTO Fato_Estado VALUES (@ESTADOSNM, @QF)
   END

SELECT * FROM Fato_Estado
