SELECT NM_FUNCIONARIO, SALARIO
FROM FUNCIONARIO 
WHERE CIDADEID IN (SELECT CIDADEID FROM CIDADE
                   WHERE ESTADOID IN (SELECT ESTADOID
				                      FROM ESTADO
									  WHERE UF ='SP'))
OR DEPTOID IN (SELECT DEPTOID FROM DEPTO
               WHERE NM_DEPTO = 'SUPORTE' OR NM_DEPTO = 'RH')
