CREATE PROCEDURE SP_LISTA_DE_FUNCIONARIO_ANO_DE_ADMISSAO
@ANO INT
AS
SELECT NM_FUNCIONARIO, NM_DEPTO, NM_CIDADE, NM_ESTADO, UF,  SALARIO, SALARIO + (SALARIO * 0.09) AS 'SALARIO COM AUMENTO', MONTH(DATA_ADMISSAO) AS 'MÊS DE ADMISSÃO',
YEAR(DATA_ADMISSAO) AS 'ANO DE ADMISSÃO', DAY(DATA_ADMISSAO) AS 'DIA',
CASE WHEN SEXO='F' THEN 'FEMININO' ELSE 'MASCULINO' END
AS 'SEXO'
FROM FUNCIONARIO AS F
INNER JOIN DEPTO AS D ON F.DEPTOID=D.DEPTOID
INNER JOIN CIDADE AS C ON F.CIDADEID=C.CIDADEID
INNER JOIN ESTADO AS E ON C.ESTADOID=E.ESTADOID
WHERE YEAR(DATA_ADMISSAO) = @ANO
ORDER BY SALARIO DESC

SP_LISTA_DE_FUNCIONARIO_ANO_DE_ADMISSAO 2002

