CREATE VIEW VW_PESQUISA_FUNCIONARIO
AS
SELECT NM_FUNCIONARIO, SEXO, CEP, ENDERECO, BAIRRO,DATA_ADMISSAO, NM_DEPTO, NM_CIDADE, NM_ESTADO, UF, SALARIO
FROM FUNCIONARIO AS F
INNER JOIN DEPTO AS D ON F.DEPTOID=D.DEPTOID
INNER JOIN CIDADE AS C ON F.CIDADEID=C.CIDADEID
INNER JOIN ESTADO AS E ON C.ESTADOID=E.ESTADOID

SELECT * FROM VW_PESQUISA_FUNCIONARIO
 
