SELECT NM_FUNCIONARIO,NM_ESTADO,NM_DEPTO
FROM FUNCIONARIO AS F
INNER JOIN DEPTO AS D ON F.DEPTOID=D.DEPTOID
INNER JOIN CIDADE AS C ON F.CIDADEID=C.CIDADEID
INNER JOIN ESTADO AS E ON C.ESTADOID=E.ESTADOID
WHERE (UF = 'SP' OR UF = 'RJ' OR UF = 'MG' OR UF = 'PR') AND
	  (NM_DEPTO = 'RH' OR NM_DEPTO = 'SUPORTE' OR NM_DEPTO = 'DIRETORIA')
