CREATE TRIGGER DELETE_FUNCIONARIO
ON FUNCIONARIO
FOR DELETE
AS
DECLARE @CIDID INT
BEGIN
      SELECT @CIDID = CIDADEID FROM DELETED

      UPDATE Fato_Cidade SET QTD_FUNCIONARIOS = QTD_FUNCIONARIOS - 1
	  WHERE FATOCIDID = @CIDID
END
