CREATE TRIGGER NOVO_FUNCIONARIO
ON FUNCIONARIO
FOR INSERT
AS
DECLARE @CIDID INT
BEGIN
      SELECT @CIDID = CIDADEID FROM INSERTED

      UPDATE Fato_Cidade SET QTD_FUNCIONARIOS = QTD_FUNCIONARIOS + 1
	  WHERE FATOCIDID = @CIDID
END
